[package]
name = "argentum_game_coordinate_system"
version = "0.7.0"
edition = "2021"
description = "Argentum: Coordinate System"
license = "AGPL-3.0-or-later"

[dependencies]
num = "0.4.3"
quickcheck = { version = "1.0.3", default-features = false }
thiserror = "1.0.63"
