[package]
name = "argentum_game_coordinate_system"
version = "0.2.0"
edition = "2021"
description = "Argentum: Coordinate System"
license = "AGPL-3.0-only"

[dependencies]
quickcheck = { version = "1.0.3", default-features = false }
